### PR TITLE
refactor: unified-message-control

### PR DESCRIPTION
**Pull request by ChristianMurphy**
adds `marker` and `test` as options to allow different ASTs to be used with message control.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@wooorm This should be ready for review. :tada:

**Comment by ChristianMurphy** [comment]
I'll take that as [lazy consensus](https://www.apache.org/foundation/voting.html#LazyConsensus).
I'm going to merge this and cut a 0.1.0 release, and open PRs downstream at remark lint and selective.

**Comment by wooorm** [comment]
Sorry about being slow, but this looks goos, thanks for merging!

**Comment by ChristianMurphy** [comment]
Cool, thanks @wooorm! :bow:

**Pull request merged**
